//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RBD.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RBD.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _0P04_SchoolReportTotalCheck {
            get {
                object obj = ResourceManager.GetObject("0P04_SchoolReportTotalCheck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _0P05_SchoolReportOpusInAuditorium {
            get {
                object obj = ResourceManager.GetObject("0P05_SchoolReportOpusInAuditorium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _0P06_SchoolReportOpusCheckResult {
            get {
                object obj = ResourceManager.GetObject("0P06_SchoolReportOpusCheckResult", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ATECardReport {
            get {
                object obj = ResourceManager.GetObject("ATECardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] AuditoriumCardReport {
            get {
                object obj = ResourceManager.GetObject("AuditoriumCardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] db {
            get {
                object obj = ResourceManager.GetObject("db", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ExamRegisteringReconciliationReport {
            get {
                object obj = ResourceManager.GetObject("ExamRegisteringReconciliationReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ExpertCardReport {
            get {
                object obj = ResourceManager.GetObject("ExpertCardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_red {
            get {
                object obj = ResourceManager.GetObject("flag_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] GovCardReport {
            get {
                object obj = ResourceManager.GetObject("GovCardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K01A_StationReservingReport {
            get {
                object obj = ResourceManager.GetObject("K01A_StationReservingReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K01B_StationAppointment {
            get {
                object obj = ResourceManager.GetObject("K01B_StationAppointment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K02_DistributedControlReport {
            get {
                object obj = ResourceManager.GetObject("K02_DistributedControlReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K03_RoomControlReport {
            get {
                object obj = ResourceManager.GetObject("K03_RoomControlReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K04_WorkerControlReport {
            get {
                object obj = ResourceManager.GetObject("K04_WorkerControlReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K06_ReadyToExamReport {
            get {
                object obj = ResourceManager.GetObject("K06_ReadyToExamReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K06g_ReadyToExamReport {
            get {
                object obj = ResourceManager.GetObject("K06g_ReadyToExamReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K07_TotalReport {
            get {
                object obj = ResourceManager.GetObject("K07_TotalReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K08_TotalWorkerControlReport {
            get {
                object obj = ResourceManager.GetObject("K08_TotalWorkerControlReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K09_FillAuditoriumsControlReport {
            get {
                object obj = ResourceManager.GetObject("K09_FillAuditoriumsControlReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] K10_ControlVerbalPlaningWokerAndAuditoriums {
            get {
                object obj = ResourceManager.GetObject("K10_ControlVerbalPlaningWokerAndAuditoriums", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OP01_ParticipantBySchool {
            get {
                object obj = ResourceManager.GetObject("OP01_ParticipantBySchool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OP02_SchoolToSchoolReport {
            get {
                object obj = ResourceManager.GetObject("OP02_SchoolToSchoolReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OP03_OpusPass {
            get {
                object obj = ResourceManager.GetObject("OP03_OpusPass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OP07_ChangeParticipantsInfo {
            get {
                object obj = ResourceManager.GetObject("OP07_ChangeParticipantsInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpusBlankRegistartion {
            get {
                object obj = ResourceManager.GetObject("OpusBlankRegistartion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpusBlankWritingOneSidedPrintingAuto {
            get {
                object obj = ResourceManager.GetObject("OpusBlankWritingOneSidedPrintingAuto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpusBlankWritingOneSidedPrintingManual {
            get {
                object obj = ResourceManager.GetObject("OpusBlankWritingOneSidedPrintingManual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpusBlankWritingTwoSidedPrintingAuto {
            get {
                object obj = ResourceManager.GetObject("OpusBlankWritingTwoSidedPrintingAuto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpusBlankWritingTwoSidedPrintingAutoBack {
            get {
                object obj = ResourceManager.GetObject("OpusBlankWritingTwoSidedPrintingAutoBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpusBlankWritingTwoSidedPrintingManual {
            get {
                object obj = ResourceManager.GetObject("OpusBlankWritingTwoSidedPrintingManual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpusBlankWritingTwoSidedPrintingManualBack {
            get {
                object obj = ResourceManager.GetObject("OpusBlankWritingTwoSidedPrintingManualBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ParticipantCardReport {
            get {
                object obj = ResourceManager.GetObject("ParticipantCardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ParticipantsQuantityReport {
            get {
                object obj = ResourceManager.GetObject("ParticipantsQuantityReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF01_RegionControl {
            get {
                object obj = ResourceManager.GetObject("PF01_RegionControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF02_GovernmentControl {
            get {
                object obj = ResourceManager.GetObject("PF02_GovernmentControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF03_AreaControl {
            get {
                object obj = ResourceManager.GetObject("PF03_AreaControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF04_SchoolControl {
            get {
                object obj = ResourceManager.GetObject("PF04_SchoolControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF05_PCenterControl {
            get {
                object obj = ResourceManager.GetObject("PF05_PCenterControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF06_SWorkersControl {
            get {
                object obj = ResourceManager.GetObject("PF06_SWorkersControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF07_ExpertsControl {
            get {
                object obj = ResourceManager.GetObject("PF07_ExpertsControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF08_StationsControl {
            get {
                object obj = ResourceManager.GetObject("PF08_StationsControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF09_SAudControl {
            get {
                object obj = ResourceManager.GetObject("PF09_SAudControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF10_ParticipantControl {
            get {
                object obj = ResourceManager.GetObject("PF10_ParticipantControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF11_ParticipantDublication {
            get {
                object obj = ResourceManager.GetObject("PF11_ParticipantDublication", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PF12_SWorkerDublication {
            get {
                object obj = ResourceManager.GetObject("PF12_SWorkerDublication", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL01_ParticipantByStation {
            get {
                object obj = ResourceManager.GetObject("PL01_ParticipantByStation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL02_SchoolToStationReport {
            get {
                object obj = ResourceManager.GetObject("PL02_SchoolToStationReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL03_SWorkerEx {
            get {
                object obj = ResourceManager.GetObject("PL03_SWorkerEx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL04_SWorkerSetting {
            get {
                object obj = ResourceManager.GetObject("PL04_SWorkerSetting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL05_Materials {
            get {
                object obj = ResourceManager.GetObject("PL05_Materials", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL06_SWorkerPlan {
            get {
                object obj = ResourceManager.GetObject("PL06_SWorkerPlan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL07_Pass {
            get {
                object obj = ResourceManager.GetObject("PL07_Pass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL09_RegistrationCodesReport {
            get {
                object obj = ResourceManager.GetObject("PL09_RegistrationCodesReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PL10_SWorkerVoice {
            get {
                object obj = ResourceManager.GetObject("PL10_SWorkerVoice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PPECardReport {
            get {
                object obj = ResourceManager.GetObject("PPECardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PPEWorkerCardReport {
            get {
                object obj = ResourceManager.GetObject("PPEWorkerCardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PPOICardReport {
            get {
                object obj = ResourceManager.GetObject("PPOICardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] R01_PResult {
            get {
                object obj = ResourceManager.GetObject("R01_PResult", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] rbdbootstrapper {
            get {
                object obj = ResourceManager.GetObject("rbdbootstrapper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;&lt;Localization language=&quot;Russian&quot; culture=&quot;Ru&quot; description=&quot;Русский&quot;&gt;&lt;Section ident=&quot;Common.QRCodeExceptions&quot;&gt;&lt;String ident=&quot;NumberOfData&quot;&gt;Длина строки не допустима&lt;/String&gt;&lt;String ident=&quot;NoPolynomialForNumber&quot;&gt;Нет полинома для этого количества кодовых слов коррекции ошибок&lt;/String&gt;&lt;String ident=&quot;ErrorCorrectionLevel&quot;&gt;Уровень коррекции ошибок недопустим для данной версии&lt;/String&gt;&lt;String ident=&quot;InvalidVersion&quot;&gt;Версия не может быть младше 0 и старше {0}&lt;/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ReporertLangRussian {
            get {
                return ResourceManager.GetString("ReporertLangRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB01_SummaryPreparationReport {
            get {
                object obj = ResourceManager.GetObject("SB01_SummaryPreparationReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB01_SummaryPreparationReport_Opus {
            get {
                object obj = ResourceManager.GetObject("SB01_SummaryPreparationReport_Opus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB01g_SummaryPreparationReport {
            get {
                object obj = ResourceManager.GetObject("SB01g_SummaryPreparationReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB02_StationWorkersReport {
            get {
                object obj = ResourceManager.GetObject("SB02_StationWorkersReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB03_PeopleCountReport {
            get {
                object obj = ResourceManager.GetObject("SB03_PeopleCountReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB03g_PeopleCountReport {
            get {
                object obj = ResourceManager.GetObject("SB03g_PeopleCountReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB04_VerifyReport {
            get {
                object obj = ResourceManager.GetObject("SB04_VerifyReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB04g_VerifyReport {
            get {
                object obj = ResourceManager.GetObject("SB04g_VerifyReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB05_ExamPreparationReport {
            get {
                object obj = ResourceManager.GetObject("SB05_ExamPreparationReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB06_PeopleCategoriesReport {
            get {
                object obj = ResourceManager.GetObject("SB06_PeopleCategoriesReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB07_StationPlacesReport {
            get {
                object obj = ResourceManager.GetObject("SB07_StationPlacesReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB07g_StationPlacesReport {
            get {
                object obj = ResourceManager.GetObject("SB07g_StationPlacesReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB08_ParticipantCountByExam {
            get {
                object obj = ResourceManager.GetObject("SB08_ParticipantCountByExam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB09_ExamDate {
            get {
                object obj = ResourceManager.GetObject("SB09_ExamDate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB10_Registration {
            get {
                object obj = ResourceManager.GetObject("SB10_Registration", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SB12_NotParticipant {
            get {
                object obj = ResourceManager.GetObject("SB12_NotParticipant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SchoolCardReport {
            get {
                object obj = ResourceManager.GetObject("SchoolCardReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap select_all {
            get {
                object obj = ResourceManager.GetObject("select_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap select_none {
            get {
                object obj = ResourceManager.GetObject("select_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ShartpshooterExpressLicense {
            get {
                object obj = ResourceManager.GetObject("ShartpshooterExpressLicense", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe1 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe10 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe111 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe111", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe111_tom {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe111_tom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe11y {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe11y", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe121 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe121", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe122 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe122", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe123 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe123", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe131 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe131", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe131_tom {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe131_tom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe132_gia {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe132_gia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe132_gia_tom {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe132_gia_tom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe133y {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe133y", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe141 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe141", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe141_ovz {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe141_ovz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe141_tom {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe141_tom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe142 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe142", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe142_tom {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe142_tom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe15 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe15_tom {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe15_tom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe16 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe18_gia {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe18_gia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe19 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe2 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe20 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe21 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe22 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe22", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe3 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe51 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe51", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe52 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe52", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe53y {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe53y", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe54y {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe54y", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe61 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe61", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe62 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe62", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe71 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe71", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe72 {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe72", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_ppe7y_gia {
            get {
                object obj = ResourceManager.GetObject("ST01_ppe7y_gia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST01_StationReports {
            get {
                object obj = ResourceManager.GetObject("ST01_StationReports", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST02_ppe52 {
            get {
                object obj = ResourceManager.GetObject("ST02_ppe52", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST02_ppe61 {
            get {
                object obj = ResourceManager.GetObject("ST02_ppe61", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST02_ppe72 {
            get {
                object obj = ResourceManager.GetObject("ST02_ppe72", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ST02_Protokol_rezultatov_GVE {
            get {
                object obj = ResourceManager.GetObject("ST02_Protokol_rezultatov_GVE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] StuffOrderByRegion {
            get {
                object obj = ResourceManager.GetObject("StuffOrderByRegion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] StuffOrderByStation {
            get {
                object obj = ResourceManager.GetObject("StuffOrderByStation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] testreport {
            get {
                object obj = ResourceManager.GetObject("testreport", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
